package views;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Random;
import ldgraph.LDGraph;
//import javax.swing.JPanel;
import models.*;

/**
 * Shows a graph containing LineDraw scores per patient
 * @author Jelle Mogony
 */
public class PatientGraph extends javax.swing.JFrame {

    /**
     * Creates new form PatientOverview2
     */
    public PatientGraph() {
        initComponents();
        /* DUMMY DATA */
//        String[] names = {"de Vries", "de Boer", "de Man", "de Aap", "van der Hoek"};
//        ArrayList<Integer> scores;// = new ArrayList();
//        ArrayList<String> dates;// = new ArrayList();
//        ArrayList<Scores> patientScores = new ArrayList();
//        Random rand = new Random();
//        
//        for (int i = 0; i < 5; i++) {
//            scores = new ArrayList();
//            dates = new ArrayList();
//            for (int j = 0; j < 10; j++) {
//                scores.add(rand.nextInt(100));
//                dates.add((j+1) + "-04");
//            }
//            patientScores.add(new Scores(names[i], scores, dates));
//        }
        /* END DUMMY DATA */
        
        graphPanel.setLayout(new BorderLayout());
        graphPanel.add(new Graph(generateDummyData(5)).getCp(), BorderLayout.CENTER);
        graphPanel.validate();
    }
    
//    private ArrayList<Score> generateDummyData(int num) {
//        num = num > 10 ? 10 : num;
//        String[] names = {"de Vries", "de Boer", "de Man", "de Aap", 
//            "van der Hoek", "Mogony", "Baas", "Goucem", "Amakran"};
//        ArrayList<Integer> scores;// = new ArrayList();
//        ArrayList<String> dates;// = new ArrayList();
//        ArrayList<Score> patientScores = new ArrayList();
//        Random rand = new Random();
//        
//        for (int i = 0; i < num; i++) {
//            scores = new ArrayList();
//            dates = new ArrayList();
//            for (int j = 0; j < 10; j++) {
//                scores.add(rand.nextInt(100));
//                dates.add((j+1) + "-04");
//            }
//            patientScores.add(new Score(names[i], scores, dates));
//        }
//        return patientScores;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jButton1.setText("< Terug");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        LDGraph.showPatientOverview();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
