package views;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JPanel;
import models.*;

/**
 * Shows a graph containing LineDraw scores per patient
 * @author Jelle Mogony
 */
public class PatientOverview extends javax.swing.JFrame {

    /**
     * Creates new form PatientOverview2
     */
    public PatientOverview() {
        initComponents();
        /* DUMMY DATA */
//        String[] names = {"de Vries", "de Boer", "de Man", "de Aap", "van der Hoek"};
//        ArrayList<Integer> scores;// = new ArrayList();
//        ArrayList<String> dates;// = new ArrayList();
//        ArrayList<Scores> patientScores = new ArrayList();
//        Random rand = new Random();
//        
//        for (int i = 0; i < 5; i++) {
//            scores = new ArrayList();
//            dates = new ArrayList();
//            for (int j = 0; j < 10; j++) {
//                scores.add(rand.nextInt(100));
//                dates.add((j+1) + "-04");
//            }
//            patientScores.add(new Scores(names[i], scores, dates));
//        }
        /* END DUMMY DATA */
        
        graphPanel.setLayout(new BorderLayout());
        graphPanel.add(new Graph(generateDummyData(5)).getCp(), BorderLayout.CENTER);
        graphPanel.validate();
    }
    
    private ArrayList<Scores> generateDummyData(int num) {
        String[] names = {"de Vries", "de Boer", "de Man", "de Aap", "van der Hoek"};
        ArrayList<Integer> scores;// = new ArrayList();
        ArrayList<String> dates;// = new ArrayList();
        ArrayList<Scores> patientScores = new ArrayList();
        Random rand = new Random();
        
        for (int i = 0; i < 5; i++) {
            scores = new ArrayList();
            dates = new ArrayList();
            for (int j = 0; j < 10; j++) {
                scores.add(rand.nextInt(100));
                dates.add((j+1) + "-04");
            }
            patientScores.add(new Scores(names[i], scores, dates));
        }
        return patientScores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jButton1.setText("Voeg Toe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
